# Generated by Django 4.2 on 2024-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author_Id',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Birth_date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Book_Id',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Pages',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Publication_year',
            new_name='publication_year',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='Genre_Id',
            new_name='genre_id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='author',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='Name',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='Default Genre Name', max_length=256),
        ),
    ]
