# Generated by Django 4.2 on 2024-04-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_description_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fragment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
